# Generated by Django 2.2.2 on 2019-06-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetail',
            table='userdetails',
        ),
    ]
